language: node_js

node_js:
  - "10"

install: npm install

cache:
  directories:
    - node_modules

script:
  - npm run test -- --coverage

after_script:
  - COVERALLS_REPO_TOKEN=$coveralls_repo_token npm run coveralls
