export const CURRENCY_LIST_REMOVE = 'CURRENCY_LIST_REMOVE';

export const CURRENCY_RATE_FETCH = 'CURRENCY_RATE_FETCH';

export const CURRENCY_RATE_FETCH_ERROR = 'CURRENCY_RATE_FETCH_ERROR';

export const CURRENCY_ERROR_CANCEL = 'CURRENCY_ERROR_CANCEL';

export const CURRENCY_RATE_ADD = 'CURRENCY_RATE_ADD';

export const CURRENCY_LOADING_STATUS = 'CURRENCY_LOADING_STATUS';

export const UI_MODAL_TOGGLE = 'UI_MODAL_TOGGLE';
