export const CURRENCY_LIST_REMOVE = 'CURRENCY_LIST_REMOVE';

export const CURRENCY_BASE_ADD = 'CURRENCY_BASE_ADD';

export const CURRENCY_SELECTED_ADD = 'CURRENCY_SELECTED_ADD';

export const UI_MODAL_TOGGLE = 'UI_MODAL_TOGGLE';
